services:

  rosbot:
    image: husarion/rosbot:humble-22-11-25
    network_mode: host
    ipc: host
    environment:
      - DDS_CONFIG
    command: ros2 launch rosbot_bringup rosbot_bringup.launch.py
  
  microros:
    image: husarion/micro-ros-agent:humble-22-11-25
    network_mode: host
    ipc: host
    devices:
      - ${SERIAL_PORT:?err}
    environment:
      - DDS_CONFIG
    command: ros2 run micro_ros_agent micro_ros_agent serial -D $SERIAL_PORT serial -b 576000 # -v6

  rplidar:
    image: husarion/rplidar:humble-22-11-25
    network_mode: host
    ipc: host
    devices:
      - ${LIDAR_SERIAL:?err}:/dev/ttyUSB0
    environment:
      - DDS_CONFIG
    command: ros2 launch sllidar_ros2 sllidar_launch.py serial_baudrate:=${LIDAR_BAUDRATE:-115200}

  navigation:
    image: husarion/navigation2:humble-22-11-25
    network_mode: host
    ipc: host
    volumes:
      - ./config/nav2_params.yaml:/nav2_params.yaml
    environment:
      - DDS_CONFIG
    command: >
      ros2 launch nav2_bringup navigation_launch.py
        params_file:=/nav2_params.yaml
        use_sim_time:=${USE_SIM_TIME:-False}

  localization:
    image: husarion/navigation2:humble-22-11-25
    network_mode: host
    ipc: host
    volumes:
      - ./config/amcl_params.yaml:/amcl_params.yaml
      - ./maps:/maps
    environment:
      - DDS_CONFIG
    command: >
      ros2 launch nav2_bringup localization_launch.py
        params_file:=/amcl_params.yaml
        map:=/maps/map.yaml
        use_sim_time:=${USE_SIM_TIME:-False}